print('==Digite seus dados Nome e Data de nascimento==')
print('')
print('^^==Nome==^^')
nome = input('Qual o seu nome? ')
print('')
print('==Data de nascimento==')
dia = input('Dia ')
mes = input('Mes ')
ano = input('Ano ')
print('Olá', nome, 'Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto?')
