txt = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(txt)}  ')
print(f'Só tem espaços? {txt.isspace()}')
print(f'É um número? {txt.isnumeric()}')
print(f'É alfanumérico? {txt.isalnum()}')
print(f'É alfabético? {txt.isalpha()}')
print(f'É minúscula? {txt.islower()}')
print(f'É maiúscula? {txt.isupper()}')
print(f'É capitalizada? {txt.istitle()}')
print(f'Valor de saida: {txt.capitalize()}')
